#include <stdint.h>
#include <stdbool.h>
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "inc/hw_types.h"
#include "inc/hw_uart.h"
#include "driverlib/gpio.h"
#include "driverlib/rom.h"
#include "driverlib/rom_map.h"
#include "driverlib/uart.h"
#include "utils/ringbuf.h"
#include "config.h"
#include "priorities.h"
#include "serial.h"
#include "telnet.h"
#include "FreeRTOSConfig.h"

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"

//wifi_web
uint8_t   tinyBuf[32];

uint8_t sbidx;//index for each line received by wifly uart
//uint8_t httpLine = 1;
uint8_t fillingPostData;
int     contentLen;
extern tRingBufObject wifi_pageRxBuf;
extern tRingBufObject wifi_pageTxBuf;

//uint8_t file[64];

enum HttpMethod httpMethod;

enum HttpMethod {
    HTTP_METHOD_GET,
    HTTP_METHOD_POST,
    HTTP_METHOD_READ_POST_DATA,
    HTTP_METHOD_GET_XML,
    HTTP_METHOD_FORCE_STARTOVER,
    HTTP_METHOD_ADVANCED_FEATURES
};
enum HttpState
{
    HTTP_CONN_WAIT,
    HTTP_CONN_WAIT1,
    HTTP_CONN_WAIT2,
    HTTP_CONN_OPEN,
	HTTP_CONN_HANDLE,
    HTTP_CONN_CLOSE,
    HTTP_CONN_CLOSE1,
};
enum HttpState  httpState;
/*
const char *Login_httpHeaders[3] =
{
		"HTTP/1.1 200 OK\r\n",
		"Connection: keep-alive\r\n",
		"Content-type: text/html\r\n\r\n"
};

const char *httpHeaders[3] =
{
		"HTTP/1.1 200 OK\r\n",
		"Connection: keep-alive\r\n",
};
*/
/*
unsigned char page2[] =
"<!DOCTYPE html>\n"
"<head>\n"
"</head>\n"
"<body>\n"
"Access Point has been reconfigured\n"
"</body>\n"
"</html>";

unsigned char page4[] =
"<!DOCTYPE html>\r\n"
"<html lang=\"en\"> \r\n"
"<head> \r\n"
"<title>Microchip EZConfig Application</title>\r\n"
"<script>\r\n"
"var xmlhttp;\r\n"
"function loadXMLDoc(url, cfunc, data)\r\n"
"{\r\n"
    "if (window.XMLHttpRequest)\r\n"
    "{\r\n"
        "xmlhttp = new XMLHttpRequest();\r\n"
        "xmlhttp.open((data==null)?\"GET\":\"POST\", url, true);\r\n"
        "xmlhttp.send(data);\r\n"
    "}\r\n"
    "else\r\n"
    "{\r\n"
        "xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n"
        "xmlhttp.open((data==null)?\"GET\":\"POST\", url, true);\r\n"
        "xmlhttp.send(data);\r\n"
    "}\r\n"
    "xmlhttp.onreadystatechange = cfunc;\r\n"
"}\r\n"
"function getXMLValue(xmlData, field, child) \r\n"
"{\r\n"
	"child = typeof(child) == \"undefined\" ? 0 : child;\r\n"

	"try {\r\n"
		"if(xmlData.getElementsByTagName(field)[child].firstChild.nodeValue)\r\n"
			"return xmlData.getElementsByTagName(field)[child].firstChild.nodeValue;\r\n"
		"else\r\n"
			"return null;\r\n"
	"} catch(err) { return null; }\r\n"
"}\r\n"
"function switchNetwork(id)\r\n"
"{\r\n"
	"var name = id;\r\n"
	"if (name == \"\")\r\n"
	"{\r\n"
		"alert('SSID cannot be left blank!');\r\n"
		"return;\r\n"
	"}\r\n"
	"document.getElementById(\"SSID2\").value = name;\r\n"
"}\r\n"

"function deleteWiFiScanTable()\r\n"
"{\r\n"
    "var table = document.getElementById('scanTable').getElementsByTagName('tbody')[0];\r\n"
    "var rows = table.rows;\r\n"

    "while (rows.length - 1)\r\n"
        "table.deleteRow(rows.length - 1);\r\n"
"}\r\n"
"function addScanRow(ssid)\r\n"
"{\r\n"
	"var tbody = document.getElementById('scanTable').getElementsByTagName(\"tbody\")[0];\r\n"
	"var row = document.createElement(\"tr\");\r\n"

	"row.setAttribute('id', ssid);\r\n"
	"row.setAttribute('onmouseover', \"this.style.cursor='pointer'\");\r\n"
        "row.setAttribute('onclick', 'switchNetwork(id);');\r\n"
	"var data1 = document.createElement(\"td\");\r\n"
	"data1.setAttribute('style', 'width:10em');\r\n"
	"data1.appendChild(document.createTextNode(ssid));\r\n"

	"row.appendChild(data1);\r\n"
	"tbody.appendChild(row);\r\n"
"}\r\n"
"function scanWiFiNetwork()\r\n"
"{\r\n"
    "deleteWiFiScanTable();\r\n"
    "loadXMLDoc('scanresults.xml?scan=1',function()\r\n"
    "{\r\n"
        "if (xmlhttp.readyState==4 && xmlhttp.status==200)\r\n"
        "{\r\n"
            "var i,x;\r\n"
             "xmlData = xmlhttp.responseXML;\r\n"
             "x = xmlhttp.responseXML.documentElement.getElementsByTagName(\"bss\");\r\n"
             "txt=\"\";\r\n"
             "for(i=0; i < x.length; i++)\r\n"
             "{\r\n"
                     "addScanRow( getXMLValue(xmlData, 'ssid', i) );\r\n"
             "}\r\n"
        "}\r\n"
   "});\r\n"
"}\r\n"
"</script>\r\n"
"<style>\r\n"
"body { \r\n"
"background-color: #312e1d;\r\n"
"font-family: tahoma, sans-serif;\r\n"
"}\r\n"
"#content {\r\n"
"margin: 20px auto;\r\n"
"width: 600px;\r\n"
"background-color: #f8f8f8;\r\n"
"padding: 20px 10px;\r\n"
"border: solid 3px red;\r\n"
"}\r\n"

"h1 {\r\n"
"font-size: 120%;\r\n"
"}\r\n"
"input[type=text] {\r\n"
"width: 400px;\r\n"
"}\r\n"
"tr.label {\r\n"
"vertical-align: top;\r\n"
"}\r\n"
"#menu {\r\n"
	"float: left;\r\n"
	"width: 150px;\r\n"
	"padding-right: 5px;\r\n"
"}\r\n"
"#menu a {\r\n"
	"width: 145px;\r\n"
	"display: block;\r\n"
	"background: #c00;\r\n"
	"color: white;\r\n"
	"padding: 5px;\r\n"
	"font-weight: bold;\r\n"
	"border-bottom: 2px solid #fff;\r\n"
	"text-decoration: none;\r\n"
"}\r\n"
"#menu a:hover {\r\n"
	"background: #d33;\r\n"
"}\r\n"
"</style>\r\n"
"</head>\r\n"
"<body>\r\n"
"<div id=\"content\">\r\n"
"<h1 style=\"text-align:center\"> Device Configuration Form </h1>\r\n"
"<div id=\"menu\">\r\n"
    "<a href=\"/index.htm\">Configure</a>\r\n"
    "<a href=\"/advance.htm\">Advanced Features</a>\r\n"
"</div>\r\n"
"<form method=\"post\" action=\"http://5.16.71.1:2000\">\r\n"
"<table>\r\n"
"<tr>\r\n"
"<td height=\"20\"></td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"<td class=\"label\">SSID</td>\r\n"
"<td class=\"form\"><input name=\"SSID\" type=\"text\" id=\"SSID2\" /></td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"<td class=\"label\">Network Password</td>\r\n"
"<td class=\"form\"><input name=\"password\" type=\"text\" /></td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"<td class=\"label\">Channel</td>\r\n"
"<td class=\"form\">\r\n"
"<select name=\"Channel\">\r\n"
"<option value=\"\">-- Select channel --</option>\r\n"
"<option value=\"0\">Search On All Channels</option>\r\n"
"<option value=\"1\">Channel 1</option>\r\n"
"<option value=\"2\">Channel 2</option>\r\n"
"<option value=\"3\">Channel 3</option>\r\n"
"<option value=\"4\">Channel 4</option>\r\n"
"<option value=\"5\">Channel 5</option>\r\n"
"<option value=\"6\">Channel 6</option>\r\n"
"<option value=\"7\">Channel 7</option>\r\n"
"<option value=\"8\">Channel 8</option>\r\n"
"<option value=\"9\">Channel 9</option>\r\n"
"<option value=\"10\">Channel 10</option>\r\n"
"<option value=\"11\">Channel 11</option>\r\n"
"</select>\r\n"
"</td>"
"</tr>"
"<tr>\r\n"
"<td class=\"label\">Auto-Join</td>\r\n"
"<td class=\"form\">\r\n"
"Enable <input type=\"radio\" name=\"AutoJoin\" value=\"Yes\"  /> &nbsp;\r\n"
"Disable <input type=\"radio\" name=\"AutoJoin\" value=\"No\" checked/> &nbsp;\r\n"
"</td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"<td height=\"20\"></td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"<td></td>\r\n"
"<td><input type=\"submit\" name=\"submit\" value=\" Enter \" /></td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"<td height=\"40\"></td>\r\n"
"</tr>\r\n"
"</table>"
        "<table id=\"scanTable\">\r\n"
    	"<tbody>\r\n"
    		"<tr>\r\n"
    			"<td colspan=\"4\">\r\n"
    				"<input id=\"rescan\" type=\"button\" style=\"width:18em\" \r\n"
    				  "value=\"View Available Wireless Networks...\" onclick=\"scanWiFiNetwork();\"></input>\r\n"
    			"</td>\r\n"
    		"</tr>\r\n"
    	"</tbody>\r\n"
        "</table>\r\n"
"</form>\r\n"
"</div>\r\n"
"</body>\r\n"
"</html>\r\n"
		"<script type=\"text/javascript\">\r\n"
		"if (window.stop)\r\n"
		"window.stop();\r\n"
		"else\r\n"
		"document.execCommand(\"Stop\");\r\n"
		"</script>";


const uint8_t lan[] = "<!DOCTYPE HTML>\n"
		"<html>\n"
		"<head>\n"
		"<title>Ethernet Settings</title>\n"
		"<script type=\"text/javascript\">\n"
		"function FindAndSelect(selectBox, value)\n"
		"{\n"
		  "var i = 0;\n"
		  "for(i = 0; i < selectBox.length; i++)\n"
		  "{\n"
		    "if(selectBox.options[i].value == value)\n"
		    "{\n"
		      "selectBox.selectedIndex = i;\n"
		      "return;\n"
		    "}\n"
		  "}\n"
		"}\n"
		"function SetFormDefaults_sw()\n"
		"{\n"
		  "FindAndSelect(document.chswitch.chsw, sw);\n"
		"}\n"
		"</script>\n"
		"</head>\n"
		"<body onLoad=\"SetFormDefaults_sw()\">\n"
		"<div id=\"heading\">\n"
		      "<table width=\"100%\">\n"
		        "<tr>\n"
		          "<td width=\"100%\">\n"
		            "<div id=\"heading_h1\">\n"
		            "ADE-7491 Series UART to Ethernet Sever Device </div>\n"
		            "<div id=\"heading_h2\"></div>\n"
				"</td>\n"
		        "</tr>\n"
		      "</table>\n"
		      "<hr><hr>\n"
		"</div>  \n"
		  "<div id=\"content\">\n"
		    "<table width=\"100%\">\n"
		      "<tbody>\n"
			  "<tr>\n"
		        	"<td>\n"
		            	"<div align=\"right\">\n"
		                    	"Logout	\n"
		                    "</a>\n"
		                    "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n"
		            	"</div>\n"
		             "</td>\n"
		        "</tr>\n"
		        "<tr>\n"
		          "<td align=\"left\" valign=\"top\" width=\"75%\">\n"
		            "<center>\n"
		              "<h2 align=\"center\">Ethernet Settings</h2>\n"
		            "</center>\n"
		            "<hr size=\"2\" width=\"100%\">\n"
		            "<h3>Ethernet Settings:</h3>\n"
		            "<p>The current settings for WLAN may be changed using the\n"
		            "form below. To make the new settings apply each time the S2E module is\n"
		            "reset, ensure that \"Make these the default settings\" is checked before\n"
		            "pressing the \"Submit\" button. If this control is not checked,\n"
		            "the changes are applied to the port but the existing\n"
		            "defaults are used whenever the module is next reset.</p>\n"
		            "<input name=\"port\" value=\"0\" type=\"hidden\">\n"
		              "<form name=\"chswitch\" action=\"chswitch.cgi\" method=\"get\">\n"
		              "<table width=\"100%\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">\n"
		                "<tbody>\n"
						    "<tr>\n"
		                    "<td class=\"gr\">Data Channel: </td>\n"
		                    "<td></td>\n"
		                    "<td>\n"
		                      "<select size=\"1\" name=\"chsw\">\n"
		                        "<option value=\"1\">LAN - COM</option>\n"
		                        "<option value=\"2\">WLAN - COM</option>\n"
		                      "</select>\n"
		                    "</td>\n"
		                  "</tr>\n"
						  "<tr>\n"
		                    "<td></td>\n"
		                    "<td align=\"center\">\n"
		                      "<input name=\"Submit\" value=\"Submit\" type=\"submit\">\n"
		                    "</td>\n"
		                    "<td style=\"text-align: center;\">\n"
		                      "<div>&nbsp;<input name=\"default\" value=\"1\" type=\"checkbox\"> Make these the default\n"
							  "settings.<br></div>\n"
		                    "</td>\n"
		                  "</tr>\n"
		                "</tbody>\n"
		              "</table>\n"
		            "</form>\n"
		          "</td>\n"
		        "</tr>\n"
		      "</tbody>\n"
		    "</table>\n"
		    "</div>\n"
		    "<div id=\"footing\">\n"
		      "<hr><hr>\n"
		      "Copyright &copy; 2015 Foxconn Incorporated.  All rights reserved.\n"
		    "</div>\n"
		  "</body>\n"
		"</html>\n"
		"<script type=\"text/javascript\">\n"
		"if (window.stop)\n"
		"window.stop();\n"
		"else\n"
		"document.execCommand(\"Stop\");\n"
		"</script>\n";

unsigned char werror[] ="<!DOCTYPE HTML>\n"
		"<!-- Copyright (c) 2014-2015 Foxconn Incorporated.  All rights reserved. -->\n"
		"<html>\n"
		 "<head>\n"
		    "<meta http-equiv=\"Content-type\" content=\"text/html;charset=UTF-8\">\n"
		    "<title>Form Parameter Error</title>\n"
		    "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\"/>\n"
		    "<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"h.ico\"/>\n"
		    "<script src=\"javascript.js\" language=\"JavaScript1.2\" charset=\"utf-8\"></script>\n"
		  "</head>\n"
		  "<body>\n"
		    "<div id=\"heading\">\n"
		      "<table width=\"100%\">\n"
		        "<tr>\n"
		          "<td>&nbsp;</td>\n"
		          "<td width=\"100%\">&nbsp;</td>\n"
		          "<td>&nbsp;</td>\n"
		        "</tr>\n"
		      "</table>\n"
		    "</div>\n"
		    "<div>\n"
		            "<table width=\"100%\">\n"
		            "<tbody>\n"
		                "<tr>\n"
		                    "<td align=\"left\" valign=\"top\" width=\"75%\">\n"
		                        "<center>\n"
		                            "<h2 align=\"center\">Parameter Error</h2>\n"
		                        "</center>\n"
		                        "<hr size=\"2\" width=\"100%\">\n"
		                        "<p align=\"center\"></p>\n"
		                        "<p align=\"center\">Oops! one of the parameters sent to the board\n"
		                            "<br>\n"
		                            "was either missing, invalid or out of range.&nbsp;</p>\n"
		                        "<p align=\"center\">Please try again!\n"
		                            "<br>\n"
		                        "</p>\n"
		                    "</td>\n"
		                "</tr>\n"
		            "</tbody>\n"
		        "</table>\n"
		    "</div>\n"
		  "</body>\n"
		"</html>\n";

*/
