################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
COM_WIFI.obj: ../COM_WIFI.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="COM_WIFI.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Status_LED_Task.obj: ../Status_LED_Task.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="Status_LED_Task.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

WiFiCMD.obj: ../WiFiCMD.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="WiFiCMD.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

WiFi_WebAccess_Task.obj: ../WiFi_WebAccess_Task.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="WiFi_WebAccess_Task.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

config.obj: ../config.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="config.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

enet_fs.obj: ../enet_fs.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="enet_fs.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

enet_s2e.obj: ../enet_s2e.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="enet_s2e.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

idle_task.obj: ../idle_task.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="idle_task.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

lwip_task.obj: ../lwip_task.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="lwip_task.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

microchipWiFi.obj: ../microchipWiFi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="microchipWiFi.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

modbus.obj: ../modbus.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="modbus.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

modbusRTU.obj: ../modbusRTU.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="modbusRTU.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

modbusTCP.obj: ../modbusTCP.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="modbusTCP.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

serial.obj: ../serial.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="serial.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

serial_task.obj: ../serial_task.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="serial_task.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

startup_ccs.obj: ../startup_ccs.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="startup_ccs.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

telnet.obj: ../telnet.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="telnet.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

watchdog.obj: ../watchdog.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/examples/boards/ek-tm4c1294xl" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/include/ipv4" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/src/core" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/lwip-1.4.1/apps" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/include" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS" --include_path="F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="watchdog.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


