################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
utils/eeprom_pb.obj: F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/utils/eeprom_pb.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="G:/Project 2015/Comunication/TI_RTOS/examples/boards/ek-tm4c1294xl" --include_path="G:/Project 2015/Comunication/TI_RTOS" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/src/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/src/include/ipv4" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/apps" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS/Source/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="utils/eeprom_pb.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/locator.obj: F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/utils/locator.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="G:/Project 2015/Comunication/TI_RTOS/examples/boards/ek-tm4c1294xl" --include_path="G:/Project 2015/Comunication/TI_RTOS" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/src/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/src/include/ipv4" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/apps" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS/Source/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="utils/locator.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/lwiplib.obj: F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/utils/lwiplib.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="G:/Project 2015/Comunication/TI_RTOS/examples/boards/ek-tm4c1294xl" --include_path="G:/Project 2015/Comunication/TI_RTOS" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/src/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/src/include/ipv4" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/apps" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS/Source/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="utils/lwiplib.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/ringbuf.obj: F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/utils/ringbuf.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="G:/Project 2015/Comunication/TI_RTOS/examples/boards/ek-tm4c1294xl" --include_path="G:/Project 2015/Comunication/TI_RTOS" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/src/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/src/include/ipv4" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/apps" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS/Source/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="utils/ringbuf.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/swupdate.obj: ../utils/swupdate.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="G:/Project 2015/Comunication/TI_RTOS/examples/boards/ek-tm4c1294xl" --include_path="G:/Project 2015/Comunication/TI_RTOS" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/src/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/src/include/ipv4" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/apps" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS/Source/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="utils/swupdate.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/uartstdio.obj: F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/utils/uartstdio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="G:/Project 2015/Comunication/TI_RTOS/examples/boards/ek-tm4c1294xl" --include_path="G:/Project 2015/Comunication/TI_RTOS" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/src/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/src/include/ipv4" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/apps" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS/Source/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="utils/uartstdio.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/ustdlib.obj: F:/USR_3_uart_demo/demo_code/TivaWare_C_Series-2.1.0.12573/utils/ustdlib.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.2/include" --include_path="F:/USR_3_uart_demo/demo_code/3_uarts_demo_190515" --include_path="G:/Project 2015/Comunication/TI_RTOS/examples/boards/ek-tm4c1294xl" --include_path="G:/Project 2015/Comunication/TI_RTOS" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/src/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/src/include/ipv4" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/ports/tiva-tm4c129/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/lwip-1.4.1/apps" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS/Source/include" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS" --include_path="G:/Project 2015/Comunication/TI_RTOS/third_party/FreeRTOS/Source/portable/CCS/ARM_CM4F" --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --ual --preproc_with_compile --preproc_dependency="utils/ustdlib.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


